# -*- coding: utf-8 -*-
"""Χρήση Κυψελιδωτών Αυτομάτων Μάθησης σε Ανταγωνιστικό Παίγνιο.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WFsbe5XXDL7Y13B95-BHmyzbNBsQfPTZ
"""

import random
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter
from matplotlib.colors import ListedColormap

class CAPlayer:
    def __init__(self, player_id, learning_rate=0.1):
        self.player_id = player_id
        self.strategies = ['R', 'S', 'P']
        # Αρχικές πιθανότητες για κάθε στρατηγική (ίσες)
        self.probabilities = {s: 1/len(self.strategies) for s in self.strategies}
        self.current_strategy = random.choice(self.strategies)
        self.score = 0
        self.learning_rate = learning_rate #Ρυθμός μάθησης
        self.opponent_memory = {}# Αποθηκεύουμε την τελευταία κίνηση που έκανε ο συγκεκριμένος αντίπαλος

    def choose_strategy(self, opponent_move_history=None):
        if opponent_move_history and self.player_id in opponent_move_history:
            last_opponent_move = opponent_move_history[self.player_id]['last_move']
            if last_opponent_move:
                winning_move = {'R': 'P', 'P': 'S', 'S': 'R'}[last_opponent_move] #Βρίσκουμε την κίνηση που κερδίζει την τελευταία κίνηση του αντιπάλου
                if self.probabilities[winning_move] > 0.6:
                    self.current_strategy = winning_move
                    return self.current_strategy

        self.current_strategy = random.choices(self.strategies, weights=[self.probabilities[s] for s in self.strategies], k=1)[0] #αλγόριθμος ανταμοιβής-ποινής
        return self.current_strategy

    def update_probabilities(self, played_strategy, result):
        if result == 'win':#Ανταμοιβή
            self.probabilities[played_strategy] += self.learning_rate * (1 - self.probabilities[played_strategy])
        elif result == 'lose':#Ποινή
            self.probabilities[played_strategy] -= self.learning_rate * self.probabilities[played_strategy]
        # Για ισοπαλία δεν αλλάζουμε την πιθανότητα

        #Διατηρήσουμε το άθροισμα στο 1
        total_prob = sum(self.probabilities.values())
        if total_prob != 0:
            adjustment_factor = 1.0 / total_prob
            for s in self.strategies:
                self.probabilities[s] *= adjustment_factor

        # Διασφάλιση ότι οι πιθανότητες δεν πέφτουν κάτω από ένα ελάχιστο όριο
        for s in self.strategies:
            self.probabilities[s] = max(0.001, min(0.999, self.probabilities[s]))

        #Κανονικοποίηση ακριβώς στο 1
        sum_probs = sum(self.probabilities.values())
        for s in self.strategies:
            self.probabilities[s] /= sum_probs

    def play_and_learn(self, opponent, my_idx, opponent_idx):
        opponent_move = opponent.choose_strategy()
        my_move = self.choose_strategy(opponent_move_history={opponent.player_id: {'last_move': opponent_move}})

        result = get_result(my_move, opponent_move)
        if result == 'win':
            self.score += 1
        elif result == 'lose':
            self.score -= 1

        #Ενημέρωση των πιθανοτήτων με βάση το αποτέλεσμα του παιχνιδιού
        self.update_probabilities(my_move, result)

        #Αποθήκευση της κίνησης του αντιπάλου
        self.opponent_memory[opponent.player_id] = {'last_move': opponent_move}

def get_result(move1, move2):
    wins = {'R': 'S', 'S': 'P', 'P': 'R'}
    if move1 == move2:
        return 'draw'
    elif wins[move1] == move2:
        return 'win'
    else:
        return 'lose'

num_cells = 50 #Συνολικός αριθμός κυψελών
num_rounds = 300 #Αριθμός βημάτων προσομοίωσης
neighborhood_size = 3# Μέγεθος γειτονιάς
num_group_a = num_cells // 2
num_group_b = num_cells - num_group_a

cells_a = [CAPlayer(player_id=f'A_{i}', learning_rate=0.03) for i in range(num_group_a)]# Ομάδα Α
cells_b = [CAPlayer(player_id=f'B_{i}', learning_rate=0.15) for i in range(num_group_b)]# Ομάδα B
all_cells = cells_a + cells_b
dominant_strategy_history = []
group_boundaries = [num_group_a - 0.5] #όριο

# Ιστορικό για την κατανομή των στρατηγικών
strategy_distribution_history_total = {'R': [], 'S': [], 'P': []}
strategy_distribution_history_a = {'R': [], 'S': [], 'P': []}
strategy_distribution_history_b = {'R': [], 'S': [], 'P': []}

for t in range(num_rounds):
    for cell in all_cells:
        cell.score = 0
    for i in range(num_cells):
        current_cell = all_cells[i]

        for offset in range(-neighborhood_size, neighborhood_size + 1):
            j = (i + offset) % num_cells
            if i != j:
                opponent_cell = all_cells[j]
                current_cell.play_and_learn(opponent_cell, my_idx=i, opponent_idx=j)
    current_round_dominant_strategies = []
    for cell in all_cells:
        dominant_strategy = max(cell.probabilities, key=cell.probabilities.get)
        current_round_dominant_strategies.append(dominant_strategy)
    dominant_strategy_history.append(current_round_dominant_strategies)
    counts_total = {'R': 0, 'S': 0, 'P': 0}
    counts_a = {'R': 0, 'S': 0, 'P': 0}
    counts_b = {'R': 0, 'S': 0, 'P': 0}
    for i, cell in enumerate(all_cells):
        dominant_strat = max(cell.probabilities, key=cell.probabilities.get)
        counts_total[dominant_strat] += 1
        if i < num_group_a: #Ομάδα Α
            counts_a[dominant_strat] += 1
        else: #Ομάδα Β
            counts_b[dominant_strat] += 1

    #Υπολογισμός ποσοστών
    for s in ['R', 'S', 'P']:
        strategy_distribution_history_total[s].append(counts_total[s] / num_cells)
        strategy_distribution_history_a[s].append(counts_a[s] / num_group_a if num_group_a > 0 else 0)
        strategy_distribution_history_b[s].append(counts_b[s] / num_group_b if num_group_b > 0 else 0)

color_map_vals = {'R': 0, 'S': 1, 'P': 2}
numeric_dominant_history = [[color_map_vals[s] for s in row] for row in dominant_strategy_history]

plt.figure(figsize=(14, 8))
plt.imshow(numeric_dominant_history, cmap='viridis', aspect='auto', origin='lower')
plt.title("Εξέλιξη Κυρίαρχης Στρατηγικής με Κυψελοειδή Αυτόματα (Δύο Ομάδες Μάθησης)")
plt.xlabel("Κυψέλες")
plt.ylabel("Γύροι")
cbar = plt.colorbar(ticks=[0, 1, 2], label='Στρατηγική')
cbar.ax.set_yticklabels(['R', 'S', 'P'])

plt.xticks(range(0, num_cells, 5))
plt.yticks(range(0, num_rounds + 1, 50))

for boundary in group_boundaries:
    plt.axvline(x=boundary, color='red', linestyle='--', linewidth=2, label='Όριο Ομάδων ΚΑ')

plt.legend()
plt.grid(True, which='both', linestyle='--', linewidth=0.5, alpha=0.7)
plt.tight_layout()
plt.show()

colors_for_strategies = {'R': 'crimson', 'P': 'steelblue', 'S': 'forestgreen'}
fig, axes = plt.subplots(3, 1, figsize=(12, 18), sharex=True) # Αυξημένο ύψος για καλύτερη οπτικοποίηση
fig.suptitle('Κατανομή Κυρίαρχων Στρατηγικών ανά Γύρο', fontsize=18, y=0.98)

# Συνολική Κατανομή
axes[0].stackplot(range(num_rounds),
                   [strategy_distribution_history_total[s] for s in ['R', 'S', 'P']],
                   labels=['Rock (R)', 'Paper (P)', 'Scissors (S)'],
                   colors=[colors_for_strategies['R'], colors_for_strategies['P'], colors_for_strategies['S']],
                   alpha=0.8)
axes[0].set_title('Συνολικός Πληθυσμός', fontsize=14)
axes[0].set_ylabel('Ποσοστό Κυψελών', fontsize=12)
axes[0].legend(loc='upper right', fontsize=10)
axes[0].set_ylim(0, 1)
axes[0].grid(True, linestyle='--', alpha=0.6)

# Κατανομή Ομάδας Α
axes[1].stackplot(range(num_rounds),
                   [strategy_distribution_history_a[s] for s in ['R', 'S', 'P']],
                   labels=['Rock (R)', 'Paper (P)', 'Scissors (S)'],
                   colors=[colors_for_strategies['R'], colors_for_strategies['P'], colors_for_strategies['S']],
                   alpha=0.8)
axes[1].set_title(f'Ομάδα A (Learning Rate: {cells_a[0].learning_rate})', fontsize=14)
axes[1].set_ylabel('Ποσοστό Κυψελών', fontsize=12)
axes[1].legend(loc='upper right', fontsize=10)
axes[1].set_ylim(0, 1)
axes[1].grid(True, linestyle='--', alpha=0.6)

# Κατανομή Ομάδας Β
axes[2].stackplot(range(num_rounds),
                   [strategy_distribution_history_b[s] for s in ['R', 'S', 'P']],
                   labels=['Rock (R)', 'Paper (P)', 'Scissors (S)'],
                   colors=[colors_for_strategies['R'], colors_for_strategies['P'], colors_for_strategies['S']],
                   alpha=0.8)
axes[2].set_title(f'Ομάδα B (Learning Rate: {cells_b[0].learning_rate})', fontsize=14)
axes[2].set_xlabel('Γύροι', fontsize=12)
axes[2].set_ylabel('Ποσοστό Κυψελών', fontsize=12)
axes[2].legend(loc='upper right', fontsize=10)
axes[2].set_ylim(0, 1)
axes[2].grid(True, linestyle='--', alpha=0.6)

plt.tight_layout(rect=[0, 0.03, 1, 0.96])
plt.show()